apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oud
  labels:
    app: oud
    release: {{ .Release.Name }}
  annotations:
    {{- if .Values.monitoring.enabled }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.ldapPort }}"
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: ldap
    port: {{ .Values.service.ldapPort }}
    targetPort: ldap
    protocol: TCP
  - name: ldaps
    port: {{ .Values.service.ldapsPort }}
    targetPort: ldaps
    protocol: TCP
  - name: admin
    port: {{ .Values.service.adminPort }}
    targetPort: admin
    protocol: TCP
  selector:
    app: oud
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-oud-headless
  labels:
    app: oud
    release: {{ .Release.Name }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: ldap
    port: {{ .Values.service.ldapPort }}
    targetPort: ldap
    protocol: TCP
  - name: ldaps
    port: {{ .Values.service.ldapsPort }}
    targetPort: ldaps
    protocol: TCP
  - name: admin
    port: {{ .Values.service.adminPort }}
    targetPort: admin
    protocol: TCP
  - name: replication
    port: {{ .Values.oud.replicationPort }}
    targetPort: replication
    protocol: TCP
  selector:
    app: oud
    release: {{ .Release.Name }}